#!/bin/bash
function usuage () {
	echo "Usuage: $0 <file_to_decrypt> <pass_list>"
	exit
}

if [[ $# -ne 2 ]]; then
	usuage
fi

if [[ -e $1 ]]; then
	if ! [[ -e $2 ]]; then
		echo "file: '$2' does not exist !"
		usuage
		exit
	fi
else
	echo "file: '$1' does not exist !"
	usuage
	exit
fi

decrypted_file="dec_file.txt"

while read passphrase; do
    if gpg --yes --batch --passphrase $passphrase -q --output $decrypted_file -d $1 &> /dev/null; then 
    echo -e "\e[1;36mDecryption successful with passphrase: \e[1;31m$passphrase\e[0m"
#	echo "matched $passphrase"
	echo -e "Check \e[1;33m $decrypted_file \e[0m to see decrypted content."
        break
    else
       echo "Failed with passphrase: $passphrase"
    fi
done < $2

# gpg --yes --batch --passphrase harry -q --output random -d $enc.gpg 2>&1 > /dev/null
